# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rehan Butt
email: me@rehanbutt.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of projects showing many of my visual based skills: UI/UX, branding, web development, illustrations, photography and fashion design.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rehanbutt.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

plugins: [jekyll-sitemap]

collections:
  projects:
    output: true
    permalink: /:path